name: Main
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    name: build and test
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Check Xcode Version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build-for-testing CODE_SIGNIN_ALLOWED=NO -scheme "ActionsWorkshop" -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Test
        run: xcodebuild test-without-building -scheme "ActionsWorkshop" -destination "platform=iOS Simulator,name=iPhone 14"
        
